module.exports = [
  // ── STRING (12) ──────────────────────────────────────────────
  {
    id: 1,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'Hello'.length",
    choices: ['4', '5', '6', 'undefined'],
    correctIndex: 1,
    explanation: 'Thuộc tính length trả về số ký tự trong chuỗi. \'Hello\' có 5 ký tự.',
  },
  {
    id: 2,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'hello'.toUpperCase()",
    choices: ['hello', 'HELLO', 'Hello', 'HELLO()'],
    correctIndex: 1,
    explanation: 'toUpperCase() chuyển tất cả ký tự trong chuỗi sang chữ HOA.',
  },
  {
    id: 3,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'WORLD'.toLowerCase()",
    choices: ['WORLD', 'world', 'World', 'wORLD'],
    correctIndex: 1,
    explanation: 'toLowerCase() chuyển tất cả ký tự trong chuỗi sang chữ thường.',
  },
  {
    id: 4,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'JavaScript'.includes('Script')",
    choices: ['true', 'false', '1', '-1'],
    correctIndex: 0,
    explanation: 'includes() kiểm tra chuỗi con có tồn tại không, trả về true hoặc false.',
  },
  {
    id: 5,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'banana'.indexOf('a')",
    choices: ['0', '1', '2', '-1'],
    correctIndex: 1,
    explanation: 'indexOf() trả về vị trí đầu tiên tìm thấy ký tự \'a\' trong \'banana\' — tại index 1.',
  },
  {
    id: 6,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'abcdef'.slice(1, 4)",
    choices: ['abc', 'bcd', 'bcde', 'abcd'],
    correctIndex: 1,
    explanation: 'slice(1, 4) lấy ký tự từ index 1 đến trước index 4, tức \'bcd\'.',
  },
  {
    id: 7,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'  hello  '.trim()",
    choices: ['  hello  ', 'hello', ' hello ', 'hello  '],
    correctIndex: 1,
    explanation: 'trim() xóa khoảng trắng ở đầu và cuối chuỗi.',
  },
  {
    id: 8,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'a,b,c'.split(',')",
    choices: ['a,b,c', "['a', 'b', 'c']", 'abc', "['a,b,c']"],
    correctIndex: 1,
    explanation: 'split(\',\') tách chuỗi tại dấu phẩy thành mảng [\'a\', \'b\', \'c\'].',
  },
  {
    id: 9,
    topic: 'string',
    question: 'Phương thức nào dùng để kiểm tra chuỗi con có nằm trong chuỗi không?',
    code: null,
    choices: ['indexOf()', 'includes()', 'slice()', 'split()'],
    correctIndex: 1,
    explanation: 'includes() trả về true/false khi kiểm tra sự tồn tại của chuỗi con.',
  },
  {
    id: 10,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'hello world'.includes('World')",
    choices: ['true', 'false', '0', '1'],
    correctIndex: 1,
    explanation: 'includes() phân biệt hoa thường. \'World\' khác \'world\' nên trả về false.',
  },
  {
    id: 11,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'testing'.indexOf('x')",
    choices: ['0', '1', '-1', 'undefined'],
    correctIndex: 2,
    explanation: 'indexOf() trả về -1 khi không tìm thấy chuỗi con trong chuỗi.',
  },
  {
    id: 12,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'hello'.slice(-2)",
    choices: ['he', 'lo', 'ell', 'o'],
    correctIndex: 1,
    explanation: 'slice(-2) lấy 2 ký tự cuối cùng của chuỗi, tức \'lo\'.',
  },

  // ── ARRAY (12) ───────────────────────────────────────────────
  {
    id: 13,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[1, 2, 3].push(4)',
    choices: ['4', '3', '[1, 2, 3, 4]', 'undefined'],
    correctIndex: 0,
    explanation: 'push() thêm phần tử vào cuối mảng và trả về độ dài mới của mảng (4).',
  },
  {
    id: 14,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[1, 2, 3].pop()',
    choices: ['1', '2', '3', '[1, 2]'],
    correctIndex: 2,
    explanation: 'pop() xóa và trả về phần tử cuối cùng của mảng.',
  },
  {
    id: 15,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[1, 2, 3].shift()',
    choices: ['1', '2', '3', '[2, 3]'],
    correctIndex: 0,
    explanation: 'shift() xóa và trả về phần tử đầu tiên của mảng.',
  },
  {
    id: 16,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[1, 2, 3].unshift(0)',
    choices: ['0', '3', '4', '[0, 1, 2, 3]'],
    correctIndex: 2,
    explanation: 'unshift(0) thêm 0 vào đầu mảng và trả về độ dài mới (4).',
  },
  {
    id: 17,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[1, 2, 3].length',
    choices: ['2', '3', '4', 'undefined'],
    correctIndex: 1,
    explanation: 'Thuộc tính length trả về số phần tử trong mảng.',
  },
  {
    id: 18,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[1, 2, 3].includes(2)',
    choices: ['true', 'false', '1', '2'],
    correctIndex: 0,
    explanation: 'includes(2) kiểm tra mảng có chứa giá trị 2 không — trả về true.',
  },
  {
    id: 19,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[1, 2, 3].indexOf(4)',
    choices: ['0', '3', '-1', 'undefined'],
    correctIndex: 2,
    explanation: 'indexOf() trả về -1 khi không tìm thấy giá trị trong mảng.',
  },
  {
    id: 20,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'const arr = [10, 20, 30];\narr[1]',
    choices: ['10', '20', '30', 'undefined'],
    correctIndex: 1,
    explanation: 'Truy cập phần tử mảng bằng index: arr[1] là phần tử thứ hai (20).',
  },
  {
    id: 21,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'const a = [1, 2];\na.push(3);\na.length',
    choices: ['2', '3', '4', 'undefined'],
    correctIndex: 1,
    explanation: 'Sau push(3), mảng có 3 phần tử nên length trả về 3.',
  },
  {
    id: 22,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'const a = [1, 2, 3];\na.pop();\na',
    choices: ['[1, 2, 3]', '[1, 2]', '[2, 3]', '3'],
    correctIndex: 1,
    explanation: 'pop() xóa phần tử cuối (3), mảng còn lại [1, 2].',
  },
  {
    id: 23,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'const a = [1, 2, 3];\na.shift();\na',
    choices: ['[1, 2, 3]', '[2, 3]', '[1, 2]', '1'],
    correctIndex: 1,
    explanation: 'shift() xóa phần tử đầu (1), mảng còn lại [2, 3].',
  },
  {
    id: 24,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[1, 2, 3].includes(\'2\')',
    choices: ['true', 'false', '1', '-1'],
    correctIndex: 1,
    explanation: 'includes() dùng so sánh nghiêm ngặt (===). Số 2 khác chuỗi \'2\' nên trả về false.',
  },

  // ── LOOP (12) ────────────────────────────────────────────────
  {
    id: 25,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let sum = 0;\nfor (let i = 1; i <= 3; i++) {\n  sum += i;\n}\nsum',
    choices: ['3', '6', '9', '0'],
    correctIndex: 1,
    explanation: 'Vòng for cộng 1 + 2 + 3 = 6.',
  },
  {
    id: 26,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let count = 0;\nwhile (count < 3) {\n  count++;\n}\ncount',
    choices: ['2', '3', '4', '0'],
    correctIndex: 1,
    explanation: 'Vòng while tăng count từ 0 đến 3 (dừng khi count === 3).',
  },
  {
    id: 27,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let result = \'\';\nfor (const ch of \'abc\') {\n  result += ch;\n}\nresult',
    choices: ['abc', 'cba', 'a,b,c', '3'],
    correctIndex: 0,
    explanation: 'for...of duyệt từng ký tự trong chuỗi \'abc\' và nối lại.',
  },
  {
    id: 28,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let total = 0;\nconst nums = [2, 4, 6];\nfor (const n of nums) {\n  total += n;\n}\ntotal',
    choices: ['6', '10', '12', '3'],
    correctIndex: 2,
    explanation: 'for...of cộng 2 + 4 + 6 = 12.',
  },
  {
    id: 29,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let i = 0;\nwhile (i < 5) {\n  i += 2;\n}\ni',
    choices: ['4', '5', '6', '2'],
    correctIndex: 2,
    explanation: 'i tăng 0 → 2 → 4 → 6. Khi i = 6, điều kiện i < 5 sai, vòng lặp dừng.',
  },
  {
    id: 30,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let s = 0;\nfor (let i = 0; i < 4; i++) {\n  s++;\n}\ns',
    choices: ['3', '4', '5', '0'],
    correctIndex: 1,
    explanation: 'Vòng for chạy 4 lần (i = 0, 1, 2, 3), mỗi lần s tăng 1 → s = 4.',
  },
  {
    id: 31,
    topic: 'loop',
    question: 'Vòng lặp nào phù hợp nhất để duyệt từng phần tử của một mảng?',
    code: null,
    choices: ['for...in', 'for...of', 'do...while', 'switch'],
    correctIndex: 1,
    explanation: 'for...of được thiết kế để duyệt giá trị của iterable như mảng và chuỗi.',
  },
  {
    id: 32,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let x = 1;\nfor (let i = 0; i < 3; i++) {\n  x *= 2;\n}\nx',
    choices: ['4', '6', '8', '16'],
    correctIndex: 2,
    explanation: 'x nhân đôi 3 lần: 1 → 2 → 4 → 8.',
  },
  {
    id: 33,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let n = 5;\nwhile (n > 0) {\n  n--;\n}\nn',
    choices: ['-1', '0', '1', '5'],
    correctIndex: 1,
    explanation: 'Vòng while giảm n từ 5 xuống 0, dừng khi n không còn lớn hơn 0.',
  },
  {
    id: 34,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let str = \'\';\nfor (let i = 0; i < 3; i++) {\n  str += i;\n}\nstr',
    choices: ['012', '123', '0123', ''],
    correctIndex: 0,
    explanation: 'Vòng for nối giá trị i (0, 1, 2) vào chuỗi → \'012\'.',
  },
  {
    id: 35,
    topic: 'loop',
    question: 'Vòng lặp for cơ bản gồm những phần nào?',
    code: null,
    choices: [
      'khởi tạo; điều kiện; bước nhảy',
      'điều kiện; khởi tạo; bước nhảy',
      'bước nhảy; điều kiện; khởi tạo',
      'khởi tạo; bước nhảy; điều kiện',
    ],
    correctIndex: 0,
    explanation: 'Cú pháp for: for (khởi tạo; điều kiện; bước nhảy) { ... }.',
  },
  {
    id: 36,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let arr = [];\nfor (let i = 1; i <= 3; i++) {\n  arr.push(i * 2);\n}\narr',
    choices: ['[1, 2, 3]', '[2, 4, 6]', '[2, 3, 4]', '[1, 4, 9]'],
    correctIndex: 1,
    explanation: 'Mỗi lần lặp push i * 2: 2, 4, 6 → mảng [2, 4, 6].',
  },

  // ── DOM (8) ──────────────────────────────────────────────────
  {
    id: 37,
    topic: 'dom',
    question: 'Phương thức nào dùng để lấy phần tử HTML theo thuộc tính id?',
    code: null,
    choices: ['querySelector()', 'getElementById()', 'getElementsByClassName()', 'createElement()'],
    correctIndex: 1,
    explanation: 'getElementById(\'myId\') trả về phần tử có id tương ứng.',
  },
  {
    id: 38,
    topic: 'dom',
    question: 'Phương thức nào dùng để chọn phần tử đầu tiên khớp với CSS selector?',
    code: null,
    choices: ['getElementById()', 'querySelector()', 'getElementsByTagName()', 'appendChild()'],
    correctIndex: 1,
    explanation: 'querySelector(\'.class\') hoặc querySelector(\'#id\') chọn phần tử đầu tiên khớp selector.',
  },
  {
    id: 39,
    topic: 'dom',
    question: 'Thuộc tính nào dùng để đọc hoặc ghi nội dung văn bản thuần của phần tử?',
    code: null,
    choices: ['innerHTML', 'textContent', 'value', 'className'],
    correctIndex: 1,
    explanation: 'textContent lấy hoặc đặt nội dung văn bản, không parse HTML.',
  },
  {
    id: 40,
    topic: 'dom',
    question: 'Sự khác biệt chính giữa textContent và innerHTML là gì?',
    code: null,
    choices: [
      'textContent parse HTML, innerHTML thì không',
      'innerHTML parse HTML, textContent chỉ là văn bản thuần',
      'Cả hai giống hệt nhau',
      'textContent chỉ dùng cho input',
    ],
    correctIndex: 1,
    explanation: 'innerHTML có thể chèn và render thẻ HTML; textContent chỉ xử lý văn bản thuần.',
  },
  {
    id: 41,
    topic: 'dom',
    question: 'Phương thức nào dùng để tạo một phần tử HTML mới?',
    code: null,
    choices: ['createElement()', 'querySelector()', 'getElementById()', 'addEventListener()'],
    correctIndex: 0,
    explanation: 'createElement(\'div\') tạo phần tử DOM mới nhưng chưa gắn vào trang.',
  },
  {
    id: 42,
    topic: 'dom',
    question: 'Đoạn code nào đúng để lấy phần tử có id là "title"?',
    code: null,
    choices: [
      'document.getElementById(\'title\')',
      'document.querySelector(\'title\')',
      'document.getElement(\'#title\')',
      'document.findById(\'title\')',
    ],
    correctIndex: 0,
    explanation: 'getElementById nhận tên id (không cần dấu #). querySelector thì cần \'#title\'.',
  },
  {
    id: 43,
    topic: 'dom',
    question: 'Sau khi tạo phần tử mới, làm sao để thêm nó vào cuối phần tử cha?',
    code: null,
    choices: ['parent.appendChild(child)', 'parent.addChild(child)', 'parent.insert(child)', 'parent.push(child)'],
    correctIndex: 0,
    explanation: 'appendChild() gắn phần tử con vào cuối danh sách con của phần tử cha.',
  },
  {
    id: 44,
    topic: 'dom',
    question: 'Đoạn code nào đúng để đổi nội dung văn bản của phần tử el?',
    code: null,
    choices: [
      'el.textContent = \'Xin chào\'',
      'el.text = \'Xin chào\'',
      'el.content = \'Xin chào\'',
      'el.setText(\'Xin chào\')',
    ],
    correctIndex: 0,
    explanation: 'Gán el.textContent = \'...\' để thay đổi nội dung văn bản hiển thị.',
  },

  // ── EVENT (6) ────────────────────────────────────────────────
  {
    id: 45,
    topic: 'event',
    question: 'Phương thức nào dùng để đăng ký hàm xử lý khi người dùng click phần tử?',
    code: null,
    choices: ['onClick()', 'addEventListener(\'click\', handler)', 'attachEvent()', 'setClick()'],
    correctIndex: 1,
    explanation: 'addEventListener(\'click\', handler) là cách chuẩn để lắng nghe sự kiện click.',
  },
  {
    id: 46,
    topic: 'event',
    question: 'event.preventDefault() dùng để làm gì?',
    code: null,
    choices: [
      'Xóa phần tử khỏi DOM',
      'Ngăn hành vi mặc định của trình duyệt',
      'Dừng vòng lặp for',
      'Ẩn phần tử trên trang',
    ],
    correctIndex: 1,
    explanation: 'preventDefault() ngăn hành vi mặc định, ví dụ submit form hoặc theo link.',
  },
  {
    id: 47,
    topic: 'event',
    question: 'Đoạn code nào đúng để chạy hàm handleClick khi nút btn được click?',
    code: null,
    choices: [
      'btn.addEventListener(\'click\', handleClick)',
      'btn.on(\'click\', handleClick)',
      'btn.click(handleClick)',
      'btn.addClick(handleClick)',
    ],
    correctIndex: 0,
    explanation: 'addEventListener nhận tên sự kiện (chuỗi) và hàm callback.',
  },
  {
    id: 48,
    topic: 'event',
    question: 'Khi nào nên dùng preventDefault() trên form?',
    code: null,
    choices: [
      'Khi muốn form tự reload trang',
      'Khi muốn xử lý submit bằng JavaScript thay vì reload trang',
      'Khi muốn xóa tất cả input',
      'Khi muốn thêm class CSS',
    ],
    correctIndex: 1,
    explanation: 'Mặc định form submit sẽ reload trang. preventDefault() giúp xử lý bằng JS.',
  },
  {
    id: 49,
    topic: 'event',
    question: 'Tham số thứ hai của addEventListener là gì?',
    code: null,
    choices: [
      'Tên sự kiện (chuỗi)',
      'Hàm callback được gọi khi sự kiện xảy ra',
      'Phần tử DOM cha',
      'Đối tượng options bắt buộc',
    ],
    correctIndex: 1,
    explanation: 'Cú pháp: element.addEventListener(event, callback). Tham số 1 là tên sự kiện.',
  },
  {
    id: 50,
    topic: 'event',
    question: 'Đoạn code nào đúng để ngăn link chuyển trang khi click?',
    code: null,
    choices: [
      'link.addEventListener(\'click\', (e) => e.preventDefault())',
      'link.addEventListener(\'click\', (e) => e.stopPage())',
      'link.preventDefault()',
      'link.addEventListener(\'prevent\', handler)',
    ],
    correctIndex: 0,
    explanation: 'Gọi e.preventDefault() trong handler click để ngăn trình duyệt điều hướng theo href.',
  },
];
