module.exports = [
  // ── STRING (1–10) ──────────────────────────────────────────────
  {
    id: 1,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'hello world'.replace('o', '0')",
    choices: ["'hell0 world'", "'hello w0rld'", "'hell0 w0rld'", "'hello world'"],
    correctIndex: 0,
    explanation: 'replace() chỉ thay thế lần xuất hiện đầu tiên, không thay tất cả.',
  },
  {
    id: 2,
    topic: 'string',
    question: 'Phương thức nào thay thế TẤT CẢ các lần xuất hiện của chuỗi con?',
    code: null,
    choices: ['replace()', 'replaceAll()', 'substring()', 'slice()'],
    correctIndex: 1,
    explanation: 'replaceAll() thay mọi lần khớp; replace() chỉ thay lần đầu (trừ khi dùng regex /g).',
  },
  {
    id: 3,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'JavaScript'.slice(-6, -1)",
    choices: ["'Script'", "'cript'", "'Scrip'", "''"],
    correctIndex: 2,
    explanation: 'slice(-6, -1) tương đương slice(4, 9), lấy từ index 4 đến trước 9 → "Scrip".',
  },
  {
    id: 4,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'JavaScript'.substring(-6, -1)",
    choices: ["'Script'", "''", "'JavaS'", "'cript'"],
    correctIndex: 1,
    explanation: 'substring() coi số âm như 0, nên substring(-6, -1) → substring(0, 0) → chuỗi rỗng.',
  },
  {
    id: 5,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'42'.padStart(5, '0')",
    choices: ["'00042'", "'42000'", "'042'", "'42'"],
    correctIndex: 0,
    explanation: 'padStart(5, "0") căn trái và thêm "0" phía trước cho đủ 5 ký tự.',
  },
  {
    id: 6,
    topic: 'string',
    question: 'padEnd(4, "*") áp dụng lên "ab" cho kết quả nào?',
    code: null,
    choices: ["'ab**'", "'**ab'", "'abab'", "'ab'"],
    correctIndex: 0,
    explanation: 'padEnd thêm ký tự phía sau cho đủ độ dài; "ab" + "**" = "ab**".',
  },
  {
    id: 7,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'banana'.replace(/a/g, 'o')",
    choices: ["'bonono'", "'bonana'", "'bonon'", "'bannno'"],
    correctIndex: 0,
    explanation: 'Regex /a/g khớp mọi chữ "a" toàn cục, thay bằng "o" → "bonono".',
  },
  {
    id: 8,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'abcdef'.substring(4, 1)",
    choices: ["'bcd'", "'abc'", "'cde'", "''"],
    correctIndex: 0,
    explanation: 'substring() tự hoán đổi nếu start > end: substring(4,1) → substring(1,4) → "bcd".',
  },
  {
    id: 9,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '`Tổng: ${2 + 3}`',
    choices: ["'Tổng: 5'", "'Tổng: ${2 + 3}'", "'Tổng: 23'", "'Tổng: 2 + 3'"],
    correctIndex: 0,
    explanation: 'Template literal `${}` đánh giá biểu thức bên trong, 2+3=5.',
  },
  {
    id: 10,
    topic: 'string',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "'  hello  '.trim().replace('hello', 'hi')",
    choices: ["'hi'", "'  hi  '", "'  hello  '", "'hi  '"],
    correctIndex: 0,
    explanation: 'trim() bỏ khoảng trắng hai đầu thành "hello", rồi replace → "hi".',
  },

  // ── ARRAY (11–20) ─────────────────────────────────────────────
  {
    id: 11,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[1, 2, 3].map(x => x * 2)',
    choices: ['[2, 4, 6]', '[1, 2, 3]', '[3, 4, 5]', '6'],
    correctIndex: 0,
    explanation: 'map() tạo mảng mới, mỗi phần tử nhân 2.',
  },
  {
    id: 12,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[1, 2, 3, 4, 5].filter(x => x % 2 === 0)',
    choices: ['[2, 4]', '[1, 3, 5]', '[2, 4, 6]', '[]'],
    correctIndex: 0,
    explanation: 'filter() giữ lại phần tử chia hết cho 2.',
  },
  {
    id: 13,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[10, 20, 30].find(x => x > 15)',
    choices: ['20', '30', 'undefined', '[20, 30]'],
    correctIndex: 0,
    explanation: 'find() trả về phần tử ĐẦU TIÊN thỏa điều kiện (>15) → 20.',
  },
  {
    id: 14,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[1, 3, 5].find(x => x % 2 === 0)',
    choices: ['undefined', 'null', '0', 'false'],
    correctIndex: 0,
    explanation: 'Không có phần tử chẵn nào, find() trả về undefined.',
  },
  {
    id: 15,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[2, 4, 6].every(x => x % 2 === 0)',
    choices: ['true', 'false', 'undefined', '[2, 4, 6]'],
    correctIndex: 0,
    explanation: 'every() kiểm tra TẤT CẢ phần tử; mọi số đều chẵn → true.',
  },
  {
    id: 16,
    topic: 'array',
    question: 'Sau khi chạy code sau, giá trị của a là gì?',
    code: 'const a = [1]; const b = a.concat([2]);\na;',
    choices: ['[1]', '[1, 2]', '[2]', '[]'],
    correctIndex: 0,
    explanation: 'concat() không thay đổi mảng gốc; a vẫn là [1], b là [1, 2].',
  },
  {
    id: 17,
    topic: 'array',
    question: 'Sau khi chạy code sau, arr và giá trị trả về là gì?',
    code: 'const arr = [1, 2, 3, 4];\nconst result = arr.slice(1, 3);',
    choices: ['result=[2,3], arr=[1,2,3,4]', 'result=[2,3], arr=[1,4]', 'result=[1,2], arr=[1,2,3,4]', 'result=[2,3,4], arr=[1]'],
    correctIndex: 0,
    explanation: 'slice() trả về bản sao phần [1..3), không đổi mảng gốc.',
  },
  {
    id: 18,
    topic: 'array',
    question: 'Sau khi chạy code sau, arr là gì?',
    code: 'const arr = [1, 2, 3, 4];\narr.splice(1, 2);\narr;',
    choices: ['[1, 4]', '[2, 3]', '[1, 2, 3, 4]', '[1, 2]'],
    correctIndex: 0,
    explanation: 'splice(1,2) xóa 2 phần tử từ index 1 (2 và 3), còn lại [1, 4].',
  },
  {
    id: 19,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[1, 2, 3].some(x => x > 2)',
    choices: ['true', 'false', '3', 'undefined'],
    correctIndex: 0,
    explanation: 'some() trả true nếu CÓ ÍT NHẤT MỘT phần tử > 2; số 3 thỏa.',
  },
  {
    id: 20,
    topic: 'array',
    question: 'Kết quả của đoạn code sau là gì?',
    code: '[1, 2, 3, 4, 5].filter(x => x > 2).map(x => x * 10)',
    choices: ['[30, 40, 50]', '[3, 4, 5]', '[10, 20, 30]', '[3, 40, 50]'],
    correctIndex: 0,
    explanation: 'filter giữ [3,4,5], map nhân 10 → [30,40,50].',
  },

  // ── LOOP (21–30) ────────────────────────────────────────────────
  {
    id: 21,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let count = 0;\nfor (let i = 0; i < 3; i++) {\n  for (let j = 0; j < 2; j++) {\n    count++;\n  }\n}\ncount;',
    choices: ['6', '5', '3', '2'],
    correctIndex: 0,
    explanation: 'Vòng ngoài 3 lần × vòng trong 2 lần = 6 lần count++.',
  },
  {
    id: 22,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let sum = 0;\nfor (let i = 0; i < 5; i++) {\n  if (i === 3) break;\n  sum += i;\n}\nsum;',
    choices: ['3', '6', '10', '0'],
    correctIndex: 0,
    explanation: 'Cộng i=0,1,2 rồi break khi i=3; sum = 0+1+2 = 3.',
  },
  {
    id: 23,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "let s = '';\nfor (let i = 0; i < 5; i++) {\n  if (i % 2 === 0) continue;\n  s += i;\n}\ns;",
    choices: ["'13'", "'024'", "'1234'", "'135'"],
    correctIndex: 0,
    explanation: 'continue bỏ qua số chẵn; chỉ nối i=1 và i=3 → "13".',
  },
  {
    id: 24,
    topic: 'loop',
    question: 'for...of duyệt mảng [10, 20, 30] sẽ lần lượt gán giá trị nào cho biến?',
    code: 'for (const item of [10, 20, 30]) { /* ... */ }',
    choices: ['10, 20, 30', '0, 1, 2', "'0', '1', '2'", 'undefined'],
    correctIndex: 0,
    explanation: 'for...of lặp qua GIÁ TRỊ phần tử, không phải index.',
  },
  {
    id: 25,
    topic: 'loop',
    question: 'for...in duyệt mảng [\'a\', \'b\'] sẽ lần lượt gán gì cho biến key?',
    code: "for (const key in ['a', 'b']) { /* ... */ }",
    choices: ["'0', '1'", "'a', 'b'", '0, 1 (number)', '1, 2'],
    correctIndex: 0,
    explanation: 'for...in trả về tên thuộc tính (index dạng chuỗi): "0", "1".',
  },
  {
    id: 26,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let sum = 0;\nfor (let i = 1; i <= 2; i++) {\n  for (let j = 1; j <= 3; j++) {\n    sum += j;\n  }\n}',
    choices: ['12', '6', '9', '3'],
    correctIndex: 0,
    explanation: 'Mỗi vòng ngoài: 1+2+3=6; chạy 2 lần → sum=12.',
  },
  {
    id: 27,
    topic: 'loop',
    question: 'break trong vòng lặp lồng nhau (không có label) sẽ thoát vòng nào?',
    code: null,
    choices: ['Chỉ vòng lặp trong cùng (inner)', 'Cả hai vòng lặp', 'Vòng lặp ngoài (outer)', 'Toàn bộ hàm'],
    correctIndex: 0,
    explanation: 'break không label chỉ thoát khỏi vòng lặp hiện tại (inner).',
  },
  {
    id: 28,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: "let str = '';\nfor (const ch of 'ab') {\n  str += ch + '-';\n}",
    choices: ["'a-b-'", "'ab-'", "'a-b'", "'0-1-'"],
    correctIndex: 0,
    explanation: 'for...of duyệt từng ký tự "a", "b" và nối thêm "-".',
  },
  {
    id: 29,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let n = 0;\nlet i = 0;\nwhile (i < 5) {\n  i++;\n  if (i === 3) continue;\n  n++;\n}\nn;',
    choices: ['4', '5', '3', '2'],
    correctIndex: 0,
    explanation: 'i chạy 1→5; bỏ qua n++ khi i=3; n tăng 4 lần (i=1,2,4,5).',
  },
  {
    id: 30,
    topic: 'loop',
    question: 'Kết quả của đoạn code sau là gì?',
    code: 'let out = [];\nfor (let i = 0; i < 3; i++) {\n  for (let j = 0; j < 3; j++) {\n    if (j === 1) break;\n    out.push(i + j);\n  }\n}\nout;',
    choices: ['[0, 1, 2]', '[0, 1, 2, 3, 4]', '[0, 2, 4]', '[0, 1]'],
    correctIndex: 0,
    explanation: 'Mỗi i chỉ push khi j=0 (break tại j=1): 0+0=0, 1+0=1, 2+0=2.',
  },

  // ── DOM (31–40) ─────────────────────────────────────────────────
  {
    id: 31,
    topic: 'dom',
    question: 'element.classList.add("active") làm gì?',
    code: null,
    choices: [
      'Thêm class "active" vào phần tử',
      'Thay thế toàn bộ class bằng "active"',
      'Xóa class "active"',
      'Kiểm tra phần tử có class "active" không',
    ],
    correctIndex: 0,
    explanation: 'classList.add() thêm một class vào danh sách class hiện có.',
  },
  {
    id: 32,
    topic: 'dom',
    question: 'element.classList.toggle("open") khi phần tử chưa có class "open" sẽ?',
    code: null,
    choices: ['Thêm class "open"', 'Xóa class "open"', 'Trả về false', 'Không làm gì'],
    correctIndex: 0,
    explanation: 'toggle() bật/tắt class: chưa có thì thêm, đã có thì xóa.',
  },
  {
    id: 33,
    topic: 'dom',
    question: 'setAttribute("data-id", "42") dùng để làm gì?',
    code: null,
    choices: [
      'Gán attribute data-id="42" lên phần tử',
      'Gán thuộc tính JavaScript dataId = 42',
      'Tạo phần tử mới có id=42',
      'Xóa attribute data-id',
    ],
    correctIndex: 0,
    explanation: 'setAttribute() đặt giá trị attribute HTML trên phần tử DOM.',
  },
  {
    id: 34,
    topic: 'dom',
    question: 'document.querySelectorAll(".item") trả về kiểu gì?',
    code: null,
    choices: ['NodeList', 'Array', 'HTMLCollection', 'Element'],
    correctIndex: 0,
    explanation: 'querySelectorAll() trả về NodeList (giống mảng nhưng không phải Array).',
  },
  {
    id: 35,
    topic: 'dom',
    question: 'NodeList từ querySelectorAll có thể gọi trực tiếp .map() không?',
    code: null,
    choices: [
      'Không, cần Array.from() hoặc [...nodeList] trước',
      'Có, NodeList là Array',
      'Có, nếu có ít nhất 1 phần tử',
      'Chỉ khi dùng forEach trước',
    ],
    correctIndex: 0,
    explanation: 'NodeList không có .map(); cần chuyển sang mảng trước.',
  },
  {
    id: 36,
    topic: 'dom',
    question: 'element.classList.contains("hidden") trả về gì nếu phần tử có class "hidden"?',
    code: null,
    choices: ['true', 'false', '"hidden"', 'undefined'],
    correctIndex: 0,
    explanation: 'contains() trả boolean: true nếu class tồn tại trên phần tử.',
  },
  {
    id: 37,
    topic: 'dom',
    question: 'element.setAttribute("href", "/home") trên thẻ <a> sẽ?',
    code: null,
    choices: [
      'Đặt attribute href="/home" trên thẻ a',
      'Chuyển hướng trình duyệt ngay lập tức',
      'Tạo thẻ <a> mới trong DOM',
      'Chỉ hoạt động với button',
    ],
    correctIndex: 0,
    explanation: 'setAttribute cập nhật attribute HTML; click mới điều hướng.',
  },
  {
    id: 38,
    topic: 'dom',
    question: 'parent.children khác parent.childNodes ở điểm nào?',
    code: null,
    choices: [
      'children chỉ chứa element nodes; childNodes gồm cả text/comment',
      'children bao gồm text nodes',
      'childNodes chỉ chứa element',
      'Hai thuộc tính giống hệt nhau',
    ],
    correctIndex: 0,
    explanation: 'children là HTMLCollection chỉ element; childNodes gồm mọi loại node.',
  },
  {
    id: 39,
    topic: 'dom',
    question: 'element.classList.remove("active") khi không có class "active" sẽ?',
    code: null,
    choices: [
      'Không làm gì, không báo lỗi',
      'Ném TypeError',
      'Xóa toàn bộ class',
      'Thêm class "active"',
    ],
    correctIndex: 0,
    explanation: 'remove() an toàn: không có class thì bỏ qua, không lỗi.',
  },
  {
    id: 40,
    topic: 'dom',
    question: 'element.getAttribute("disabled") trên <button disabled> trả về?',
    code: null,
    choices: ['"" (chuỗi rỗng)', 'true', 'false', 'null'],
    correctIndex: 0,
    explanation: 'Attribute boolean không giá trị trả về chuỗi rỗng "", không phải true.',
  },

  // ── EVENT (41–50) ─────────────────────────────────────────────
  {
    id: 41,
    topic: 'event',
    question: 'event.target trong handler click trỏ tới đâu?',
    code: null,
    choices: [
      'Phần tử thực sự được click (có thể là con)',
      'Phần tử gắn addEventListener',
      'document.body',
      'window',
    ],
    correctIndex: 0,
    explanation: 'target là phần tử kích hoạt sự kiện; currentTarget là phần tử gắn listener.',
  },
  {
    id: 42,
    topic: 'event',
    question: 'event.currentTarget khác event.target khi click vào <span> bên trong <button> có listener?',
    code: null,
    choices: [
      'currentTarget là button, target là span',
      'Cả hai đều là span',
      'Cả hai đều là button',
      'currentTarget là span, target là button',
    ],
    correctIndex: 0,
    explanation: 'Listener trên button: currentTarget=button, target=span (phần tử được click).',
  },
  {
    id: 43,
    topic: 'event',
    question: 'Event bubbling là gì?',
    code: null,
    choices: [
      'Sự kiện lan từ phần tử con lên phần tử cha',
      'Sự kiện lan từ cha xuống con',
      'Sự kiện chỉ chạy một lần trên target',
      'Hủy sự kiện mặc định của trình duyệt',
    ],
    correctIndex: 0,
    explanation: 'Bubbling: sau target, sự kiện nổi bọt lên các ancestor.',
  },
  {
    id: 44,
    topic: 'event',
    question: 'event.stopPropagation() làm gì?',
    code: null,
    choices: [
      'Ngăn sự kiện lan lên phần tử cha',
      'Ngăn hành vi mặc định (như submit form)',
      'Xóa listener',
      'Dừng vòng lặp JavaScript',
    ],
    correctIndex: 0,
    explanation: 'stopPropagation() chặn bubbling; preventDefault() chặn hành vi mặc định.',
  },
  {
    id: 45,
    topic: 'event',
    question: 'Sự kiện "input" trên <input type="text"> kích hoạt khi nào?',
    code: null,
    choices: [
      'Mỗi khi giá trị thay đổi (gõ phím)',
      'Chỉ khi blur (rời khỏi ô)',
      'Chỉ khi nhấn Enter',
      'Chỉ khi submit form',
    ],
    correctIndex: 0,
    explanation: 'input fire liên tục khi người dùng gõ; change thường fire khi commit.',
  },
  {
    id: 46,
    topic: 'event',
    question: 'Sự kiện "change" trên <select> kích hoạt khi nào?',
    code: null,
    choices: [
      'Khi người dùng chọn option khác',
      'Mỗi lần di chuột qua',
      'Khi trang load xong',
      'Khi nhấn phím bất kỳ',
    ],
    correctIndex: 0,
    explanation: 'change trên select fire khi giá trị được chọn thay đổi.',
  },
  {
    id: 47,
    topic: 'event',
    question: 'Sự kiện "keydown" xảy ra khi nào?',
    code: null,
    choices: [
      'Khi phím được nhấn xuống',
      'Khi phím được thả ra',
      'Sau khi ký tự hiện trong input',
      'Chỉ với phím Enter',
    ],
    correctIndex: 0,
    explanation: 'keydown khi nhấn phím; keyup khi thả; input sau khi giá trị đổi.',
  },
  {
    id: 48,
    topic: 'event',
    question: 'Click vào <li> bên trong <ul id="list"> có listener trên ul — thứ tự bubbling?',
    code: 'list.addEventListener("click", handler);',
    choices: [
      'li (target) → ul → ... → document',
      'ul → li → document',
      'document → ul → li',
      'Chỉ chạy handler trên ul',
    ],
    correctIndex: 0,
    explanation: 'Bubbling bắt đầu tại target (li) rồi lan lên ul, body, document.',
  },
  {
    id: 49,
    topic: 'event',
    question: 'Trên <input type="text">, "input" khác "change" ở điểm nào?',
    code: null,
    choices: [
      'input fire mỗi ký tự; change fire khi blur hoặc Enter',
      'change fire mỗi ký tự; input chỉ khi blur',
      'Hai sự kiện giống hệt nhau',
      'input chỉ fire với checkbox',
    ],
    correctIndex: 0,
    explanation: 'input: realtime mỗi thay đổi; change: thường sau khi commit (blur/Enter).',
  },
  {
    id: 50,
    topic: 'event',
    question: 'Trong handler keydown, event.key === "Enter" dùng để?',
    code: null,
    choices: [
      'Phát hiện người dùng nhấn phím Enter',
      'Submit form tự động không cần code',
      'Chặn mọi phím khác Enter',
      'Focus vào input',
    ],
    correctIndex: 0,
    explanation: 'event.key cho biết phím nào được nhấn; so sánh "Enter" để xử lý.',
  },
];
